### ISSUE TITLE
Redundant body tag

### ISSUE THREAD

**Issue by shivagoud** [sbgoud/converter#1]
https://github.com/sbgoud/converter/blob/f48f10450bd43bd5fcde93b077743187094cc6c3/src/App.js#L7

There can't be multiple body tags in a document. The body tag is already added in `public/index.html` file.

**Comment by sbgoud** [comment]
okay, noted.

**Comment by shivagoud** [comment]
Create a branch to just fix this issue. Create a PR. Attach this issue inside the PR. When PR merges, this issue automatically gets closed.

**Comment by shivagoud** [comment]
Add me as a reviewer for PR

**Comment by shivagoud** [comment]
This is how all open source repositories operate. Check this example: https://github.com/mui/material-ui/issues

**Comment by sbgoud** [comment]
removed body tag, created pr, attached the issue and added you as reviewer
